# Generated by Django 5.1.4 on 2025-01-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appt',
            name='owner',
        ),
        migrations.AddField(
            model_name='appt',
            name='services',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
